version: 1.2
workflows:
        - name: goleft-wdl
        subcalss: WDL
        primaryDescriptorPath: /goleft_functions.wdl
        testParameterFiles:
            - /goleft_terra.json
        filters:
          branches:
            - master